# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Release

on:
  workflow_dispatch

jobs:
  setup:
    name: Setup
    uses: tlslink/vpnagent/.github/workflows/release-setup.yml@main
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux]
        include:
        - build: linux
          os: ubuntu-20.04
          archive-name: speedtest-go_linux_amd64.tar.gz
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20.3
    - name: Install dependencies
      run: go get .
    - name: Build
      shell: bash
      run: |
        if [ "${{ matrix.build }}" = "linux" ]; then
          go build -ldflags "-w -s" -trimpath -o speedtest-go main.go
        fi
    - name: Build archive
      shell: bash
      run: |
        mkdir speedtest
        cp settings.toml speedtest/
        # ls -lR
        if [ "${{ matrix.build }}" = "linux" ]; then
          cp speedtest-go ./speedtest/speedtest
          # cd speedtest
          tar -czf "${{ matrix.archive-name }}" ./speedtest
        fi
    - name: Upload archive
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.archive-name }}
        path: ${{ matrix.archive-name }}
        
    - name: Continuous release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/heads/')
      with:
        prerelease: false
        files: ${{ matrix.archive-name }}
        tag_name: continuous
